# Week 1 - Intro-basics lesson

---
title: "GitHub R Intro"
author: "Clara Feigelson"
date: "`r Sys.Date()`"
output: html_document
---

### Set up

```{r}
# Call setup.R code so that all necessary packages are loaded
source("setup.R")
```

### 6.1 The penguins data

```{r}
# Call/load penguin data into environment (initial upload calls it "raw")
data("penguins")

# Calls penguin dataset as a dataframe (tibble)
penguins

```

### 6.2 Data Types

```{r}
# class () describes the data type of the object
class(penguins)
# str () shows the structure of the object --> in this case the structure of the penguins tibble
str(penguins)

class(penguins$species)
str(penguins$species)
```

```{r}
# myList object
myList <- list("apple", 1993, FALSE, penguins)
str(myList)
list(myList, list("more stuff here", list("and more")))
names(myList) <- c("fruit", "year", "logic", "data")
names(myList)
```

### 6.3 Indexing

```{r}
# Code copied from the lesson

# for lists we use double brackes [[]]
myList[[1]]

myList[["data"]]

# for vectors we use single brackets []
myVector <- c("apple", "banana", "pear")
myVector[2]

# dataframe[row(s), columns()]
penguins[1:5, 2]

penguins[1:5, "island"]

penguins[1, 1:5]

penguins[1:5, c("species","sex")]

penguins[penguins$sex=='female',]

# $ for a single column
penguins$species

```

## 6.3.1 Exercises

```{r} Question 1}
myList["fruit"]

penguins$flipper_length_mm

penguins[penguins$island=='Dream',]

```

```{r} Question 2}
unique(penguins$species, incomparables = FALSE)

unique(penguins$island, incomparables = FALSE)
```

```{r}Question 3}
index1<-penguins[, c("species","island","flipper_length_mm")]

index1<-index1[index1$island=='Dream',]

```

```{r}Question 4}
# using & in base R allows you to index based on multiple criteria in a row
index2<-penguins[penguins$island=='Dream' & penguins$species == 'Adelie',]

mean(index2$flipper_length_mm)
```

### 6.4 The dplyr package

```{r}
# Copied from lesson plan

## subset rows with filter()
filter(penguins, species == "Adelie")

filter(penguins, species != "Adelie")

# indexes all penguins from Dream and Torgersen islands that are not missing data for bill_length_mm
filter(penguins, island %in% c("Dream", "Torgersen") & !is.na(bill_length_mm))

## Select columns with select()

# Select two specific variables
select(penguins, species, sex)

# Select a range of variables
select(penguins, species:flipper_length_mm)

# Rename columns within select
select(penguins, genus = species, island)

# Select column variables that are recorded in mm
select(penguins, contains("mm"))

## create new variables with mutate()

# New variable that calculates bill length in cm
mutate(penguins, bill_length_cm = bill_length_mm/10)

# mutate based on conditional statements
mutate(penguins, species_sex = if_else(sex == 'male', paste0(species,"_m"), paste0(species, "_f")))
```

### 6.4.1 The pipe %\>%

```{r}
# Copied from lesson plan

penguins %>% 
  filter(island == "Dream") %>% 
  mutate(flipper_length_cm = flipper_length_mm/10) %>% 
  select(species, year, flipper_length_cm)

# average body mass by species
penguins %>% 
  group_by(species) %>% 
  summarise(body_mass_avg = mean(body_mass_g, na.rm = TRUE))

# count of species by year
penguins %>% 
  group_by(species, year) %>% 
  summarise(n_observations = n())
```

## 6.3.2 Exercises

```{r} Question 1}
penguins %>%
  select(year, everything())

```

```{r} Question 2}
penguins %>%
  add_column(size_group = 0) %>%
  mutate(size_group = if_else(body_mass_g > mean(body_mass_g,na.rm  = TRUE), 'large', 'small'))

```

```{r} Question 3}
penguins %>%
  group_by(year, species) %>%
  summarise(body_mass_avg = mean(body_mass_g, na.r = TRUE)) %>%
  arrange(desc(body_mass_avg))
  
```

```{r} Question 4}
penguins %>% 
  filter(!(year %in% c(2008, 2009)))
```
